name: PIPNIC
favicon: null
layout_spectrum: 0.13282
typography_spectrum: 0.22354
title: test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100f0d'
    - '#fbfcf7'
    - '#595954'
    - '#43c4ef'
    - '#ffa136'
  brandStrength: 0.5625
  lightness: 0.625
  saturation: 0.6875
  rhythmicContrast: 0.25
purpose: []
