name: PIPNIC
favicon: null
layout_spectrum: 0.964057584758848
typography_spectrum: 0.4085182959679514
title: test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.7151206023991108
  lightness: 0.2058079126290977
  saturation: 0.5573137081228197
  rhythmicContrast: 0.48333763354457915
purpose: []
