name: PIPNIC
favicon: null
layout_spectrum: 0.13282
typography_spectrum: 0.4085182959679514
title: test
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#100f0d'
    - '#fbfcf7'
    - '#595954'
    - '#43c4ef'
    - '#ffa136'
  brandStrength: 0.5625
  lightness: 0.2058079126290977
  saturation: 0.5573137081228197
  rhythmicContrast: 0.48333763354457915
purpose: []
